In [ ]:
from pysolar.solar import get_altitude, get_azimuth
from datetime import datetime
from pytz import timezone
import numpy as np

def getSolarPosition(
    latitude: float = -0.2105367,
    longitude: float = -78.491614,
    date: datetime = None,
):
    """
    Obtiene la posición solar (azimut y altitud) para una fecha y ubicación específicas.

    Parametros:
    latitude (float): Latitud de la ubicación. El valor predeterminado es -0.2105367.
    longitude (float): Longitud de la ubicación. El valor predeterminado es -78.491614.
    date (datetime): Fecha y hora para la cual se desea obtener la posición solar. Si no se proporciona, se usa la fecha y hora actual.

    Retorna:
    tuple: Azimut y altitud del sol en radianes.
    """
    if date is None:
        date = datetime.now(tz=timezone("America/Guayaquil"))
    
    az = get_azimuth(latitude, longitude, date)
    el = get_altitude(latitude, longitude, date)

    return np.radians(az), np.radians(el)

az, el = getSolarPosition(-0.2105367, -78.491614, datetime.now(tz=timezone("America/Guayaquil")))
print("Azimuth (°):", np.degrees(az))
print("Elevation (°):", np.degrees(el))

roll = np.arcsin(np.sin(az) * np.cos(el))
pitch = np.arcsin(-((np.cos(az) * np.cos(el)) / np.cos(roll)))
pitch_deg = np.degrees(pitch)
comprobacion = np.arccos(np.cos(pitch))

print("Roll (°):", roll)
print("Pitch (°):", pitch_deg)
print("Comprobacion (°):", np.degrees(comprobacion))

Azimuth (°): 255.00696810562158
Elevation (°): 17.38866980451007
Roll (°): -1.1727305980326381
Pitch (°): 39.55977680888065
Comprobacion (°): 39.55977680888065


In [23]:
from pysolar.solar import get_altitude, get_azimuth
from datetime import datetime
from pytz import timezone
import numpy as np

def getSolarPosition(latitude=-0.2105367, longitude=-78.491614, date=None):
    """
    Calcula el azimuth y la elevación del sol para una posición geográfica y fecha dada.
    """
    if date is None:
        date = datetime.now(tz=timezone("America/Guayaquil"))
    
    az = get_azimuth(latitude, longitude, date)
    el = get_altitude(latitude, longitude, date)
    
    return np.radians(az), np.radians(el)

def calculate_roll_pitch(azimuth, elevation):
    """
    Calcula los ángulos de roll (β) y pitch (ϕ) para que el panel solar sea perpendicular a la luz solar.
    """
    # Cálculo de roll (β)
    roll = np.arcsin(np.sin(azimuth) * np.cos(elevation))
    
    # Cálculo de pitch (ϕ) usando dos ecuaciones de validación
    pitch_1 = np.arcsin(-((np.cos(azimuth) * np.cos(elevation)) / np.cos(roll)))
    pitch_2 = np.arccos(np.sin(elevation) / np.cos(roll))
    
    return np.degrees(roll), np.degrees(pitch_1), np.degrees(pitch_2)

# Obtener la posición solar actual
az, el = getSolarPosition()
print("Azimuth (°):", np.degrees(az))
print("Elevation (°):", np.degrees(el))

# Calcular los ángulos de control
roll_deg, pitch1_deg, pitch2_deg = calculate_roll_pitch(az, el)
print("Roll (°):", roll_deg)
print("Pitch (°) [Ecuación 1]:", pitch1_deg)
print("Pitch (°) [Ecuación 2]:", pitch2_deg)

# Calcular la matriz de rotación en el eje Norte (X) usando el ángulo de roll
roll_rad = np.radians(roll_deg)
R_N = np.array([
    [np.cos(roll_rad), 0, np.sin(roll_rad)],
    [0, 1, 0],
    [-np.sin(roll_rad), 0, np.cos(roll_rad)]
])

print("Matriz de Rotación en el eje Norte:")
print(R_N)

Azimuth (°): 255.48427405442604
Elevation (°): -8.076398024565933
Roll (°): -73.431019518999
Pitch (°) [Ecuación 1]: 60.484019885557814
Pitch (°) [Ecuación 2]: 119.51598011444203
Matriz de Rotación en el eje Norte:
[[ 0.2851695  0.        -0.9584771]
 [ 0.         1.         0.       ]
 [ 0.9584771  0.         0.2851695]]


In [22]:
from pysolar.solar import get_altitude, get_azimuth
from datetime import datetime
from pytz import timezone
import numpy as np

def getSolarPosition(latitude=-0.2105367, longitude=-78.491614, date=None):
    """
    Calcula el azimuth y la elevación del sol para una posición geográfica y fecha dada.
    """
    if date is None:
        date = datetime.now(tz=timezone("America/Guayaquil"))
    
    az = get_azimuth(latitude, longitude, date)
    el = get_altitude(latitude, longitude, date)
    
    return np.radians(az), np.radians(el)

def calculate_roll_pitch(azimuth, elevation):
    """
    Calcula los ángulos de roll (β) y pitch (ϕ) para que el panel solar sea perpendicular a la luz solar.
    """
    # Cálculo de roll (β)
    roll = np.arcsin(np.sin(azimuth) * np.cos(elevation))
    
    # Cálculo de pitch (ϕ) usando dos ecuaciones de validación
    pitch_1 = np.arcsin(-((np.cos(azimuth) * np.cos(elevation)) / np.cos(roll)))
    pitch_2 = np.arccos(np.sin(elevation) / np.cos(roll))
    
    return np.degrees(roll), np.degrees(pitch_1), np.degrees(pitch_2)

# Obtener la posición solar actual
az, el = getSolarPosition()
print("Azimuth (°):", np.degrees(az))
print("Elevation (°):", np.degrees(el))

# Calcular los ángulos de control
roll_deg, pitch1_deg, pitch2_deg = calculate_roll_pitch(az, el)
print("Roll (°):", roll_deg)
print("Pitch (°) [Ecuación 1]:", pitch1_deg)
print("Pitch (°) [Ecuación 2]:", pitch2_deg)

# Calcular la matriz de rotación en el eje Norte (eje X) usando el ángulo de roll
roll_rad = np.radians(roll_deg)
R_N = np.array([
    [1, 0, 0],  # Rotación alrededor del eje X (Norte)
    [0, np.cos(roll_rad), -np.sin(roll_rad)],
    [0, np.sin(roll_rad), np.cos(roll_rad)]
])

print("Matriz de Rotación en el eje Norte (Roll):")
print(R_N)

Azimuth (°): 255.50723097565864
Elevation (°): -7.475108380480897
Roll (°): -73.72979915448872
Pitch (°) [Ecuación 1]: 62.33190938204727
Pitch (°) [Ecuación 2]: 117.66809061795286
Matriz de Rotación en el eje Norte (Roll):
[[ 1.          0.          0.        ]
 [ 0.          0.28016748  0.95995114]
 [ 0.         -0.95995114  0.28016748]]
